---
driver:
  name: vagrant
  customize:
    natdnshostresolver1: "on"
  network:
    - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]
    - ["forwarded_port", {guest: 443, host: 8443, auto_correct: true}]

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.9.41

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[nginx-chef::install]
      - recipe[nginx-chef::config]
      - recipe[nginx-chef::welcome]
      - recipe[nginx-chef::service]
    attributes:
      dev_mode: true
